jQueryAjaxModal/jQueryAjaxModal/Models/Job.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jQueryAjaxModal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job()
        {
            this.JobEmployees = new HashSet<JobEmployee>();
        }
        public short ID { get; set; }
        [Required(ErrorMessage = "This field is required.")]
        [Display(Name = "Tên công việc")]
        public string Name { get; set; }
        [Required(ErrorMessage = "This field is required.")]
        [Display(Name = "Mức lương")]
        public decimal Salary { get; set; }
        [Display(Name = "Ngày tạo")]
        [DataType(DataType.DateTime), Required(ErrorMessage = "This field is required.")]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd HH:mm}", ApplyFormatInEditMode = true)]
        public System.DateTime Datecreated { get; set; }
        [Required(ErrorMessage = "This field is required.")]
        [Display(Name = "Kích hoạt")]
        public bool Activated { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobEmployee> JobEmployees { get; set; }
    }
}

jQueryAjaxModal/jQueryAjaxModal/Models/JobViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace jQueryAjaxModal.Models
{
    public class JobViewModel
    {
        [Key]
        public short ID { get; set; }
        [Required(ErrorMessage = "This field is required.")]
        [Display(Name = "Tên công việc")]
        public string Name { get; set; }
        [Required(ErrorMessage = "This field is required.")]
        [Display(Name = "Mức lương")]
        public decimal Salary { get; set; }
        [Display(Name = "Ngày tạo")]
        [DataType(DataType.DateTime), Required(ErrorMessage = "This field is required.")]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd HH:mm}", ApplyFormatInEditMode = true)]
        public System.DateTime Datecreated { get; set; }
        [Required(ErrorMessage = "This field is required.")]
        [Display(Name = "Kích hoạt")]
        public bool Activated { get; set; }

    }
}

jQueryAjaxModal/jQueryAjaxModal/Controllers/JobController.cs
using jQueryAjaxModal.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace jQueryAjaxModal.Controllers
{
    public class JobController : Controller
    {
        private JobDBEntities db = new JobDBEntities();
        // GET: Job
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult GetJobs()
        {
            List<Job> jobs = db.Jobs.ToList();
            

            var items = jobs.Select(row => new JobViewModel() {ID = row.ID,
                Name = row.Name,
                Salary = row.Salary,
                Datecreated = row.Datecreated,
                Activated = row.Activated });

            return Json(new { data = items }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult AddOrEdit(int id = 0)
        {
            if (id == 0)
                return View(new Job());
            else
            {
                Job job = db.Jobs.Where(model => model.ID == id).FirstOrDefault();
                return View(job);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddOrEdit(Job job)
        {
            if (job.ID == 0)
            {
                db.Jobs.Add(job);
                db.SaveChanges();
                return Json(new { success = true, message = "Inserted successfully" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                db.Entry(job).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return Json(new { success = true, message = "Updated successfully" }, JsonRequestBehavior.AllowGet);
            }

        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            Job job = db.Jobs.Where(model => model.ID == id).FirstOrDefault();
            var jobEmpToDelete = db.JobEmployees.Where(x => x.Job.ID == job.ID);
            db.JobEmployees.RemoveRange(jobEmpToDelete);
            db.Jobs.Remove(job);
            db.SaveChanges();
            return Json(new { success = true, message = "Deleted successfully" }, JsonRequestBehavior.AllowGet);
        }


    }
}

jQueryAjaxModal/jQueryAjaxModal/Views/Job/AddOrEdit.cshtml
@model jQueryAjaxModal.Models.Job
@{
    Layout = null;
}


@using (Html.BeginForm("AddOrEdit", "Job", FormMethod.Post, new { onsubmit = "return SubmitForm(this)" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Salary, htmlAttributes: new { @class = "control-label " })
            @Html.EditorFor(model => model.Salary, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Salary, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Datecreated, htmlAttributes: new { @class = "control-label " })
            @Html.EditorFor(model => model.Datecreated, new { htmlAttributes = new { @class = "form-control datepicker" , value = "" } })
            @Html.ValidationMessageFor(model => model.Datecreated, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Activated, htmlAttributes: new { @class = "control-label " })
            <div class="checkbox">
                @Html.EditorFor(model => model.Activated, new { htmlAttributes = new { @class = " form-control" } })
                @Html.ValidationMessageFor(model => model.Activated, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit" class="btn btn-sm btn-primary form-control" />
            </div>
        </div>
    </div>
}
<script>
    $(".datepicker").datetimepicker({
        startDate: new Date()
    });
</script>

jQueryAjaxModal/jQueryAjaxModal/Views/Job/Index.cshtml
@{
    ViewBag.Title = "Index";
}


<h2>Job CRUD Operations</h2>

<a class="btn btn-sm btn-success" style="margin:10px 0px;" onclick="PopupForm('@Url.Action("AddOrEdit","Job")')">Thêm công việc mới</a>
<table id="employeeTable" class="display table .table-sm">
    <thead>
        <tr>
            <th>Mã</th>
            <th>Tên công việc</th>
            <th>Mức lương</th>
            <th>Ngày tạo</th>
            <th>Kích hoạt</th>
            <th></th>
        </tr>
    </thead>
</table>

<a href="#" id="notify" class="btn btn-dark" onclick="Notify()">notify</a>

<link href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet" />
@section scripts{

    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script language="javascript" type="text/javascript">

        var Popup, dataTable;
        $(document).ready(function () {

            dataTable = $('#employeeTable').DataTable({
                "ajax": {
                    "url": "/Job/GetJobs",
                    "type": "GET",
                    "dataType": "json"
                },
                "columns": [
                    { "data": 'ID' },
                    { "data": 'Name' },
                    { "data": 'Salary' },
                    {
                        "data": 'Datecreated', 'render': function (data) { return ToJavaScriptDate(data); }
                    },
                    { "data": 'Activated' },
                    { "data": 'ID', "render": function (data) {
                        return "<a class='btn btn-primary btn-sm' onclick=PopupForm('@Url.Action("AddOrEdit", "Job")/" + data + "')><i class='fa fa-pencil'></i> Edit </a> <a class='btn btn-danger btn-sm' onclick='Delete("+data+")'><i class='fa fa-trash'></i> Delete </a>" }
                    }
                ],
                "language": {
                    "emptyTable": "No data"
                },
                "orderable": false,
                "width": "150px"
            });



        });
        function ToJavaScriptDate(value) {
            var pattern = /Date\(([^)]+)\)/;
            var results = pattern.exec(value);
            var dt = new Date(parseFloat(results[1]));
            return (dt.getMonth() + 1) + "-" + dt.getDate() + "-" + dt.getFullYear();
        }

        function PopupForm(url) {
            var formDiv = $('<div/>');
            $.get(url).done(function (response) {
                formDiv.html(response);

                Popup = formDiv.dialog({
                    autoOpen: true,
                    show: { effect: 'scale', duration: 250 },
                    hide: { effect: 'drop', duration: 100 },
                    resizable: false,
                    title: "Điền thông tin công việc",
                    height: 600,
                    width: 400,
                    close: function () {
                        Popup.dialog('destroy').remove();
                    }
                });
            });
        }

        function SubmitForm(form) {
            $.validator.unobtrusive.parse(form);
            if ($(form).valid()) {
                $.ajax({
                    type: "POST",
                    url: form.action,
                    data: $(form).serialize(),
                    success: function (data) {
                        if (data.success) {
                            Popup.dialog('close');
                            dataTable.ajax.reload();

                            $.notify(data.message, {
                                globalPosition: "right bottom",
                                className: "success"
                            })
                        }
                    }
                });
            }
            return false;
        }

        function Notify() {
            $.notify("success", {
                globalPosition: "right bottom",
                className: "success",
                showAnimation: "fadeIn",
                hideAnimation: "fadeOut",
                autoHideDelay: 1000,
            })
        }


        function Delete(id) {
            $.confirm({
                title: 'Confirm Delete!',
                content: 'Do you want to delete this record?',
                buttons: {
                    confirm: function () {
                        $.ajax({
                            type: "POST",
                            url: '@Url.Action("Delete", "Job")/' + id,
                            success: function (data) {
                                if (data.success) {
                                    dataTable.ajax.reload();

                                    $.notify(data.message, {
                                        globalPosition: "right bottom",
                                        className: "warn"
                                    });
                                    return;
                                }
                                else {
                                    $.notify(data.message, {
                                        globalPosition: "right bottom",
                                        className: "warn"
                                    });
                                }
                                
                            }
                        });
                    },
                    cancel: function () {
                        $.alert('Canceled!');
                    }
                }
            });
        }

    </script>
}